apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgres.fullname" . }}-credentials
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.auth.password | quote }}

