apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "frontend.fullname" . }}-config
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
data:
  app-config.json: |
    {
      "banner": {{ .Values.config.banner | quote }},
      "apiBaseUrl": {{ .Values.config.apiBaseUrl | quote }},
      "featureFlags": {{ .Values.config.featureFlags | toJson }}
    }

